ActivityBackgroundColor ClassFontStyle FolderStereotypeFontSize
NoteFontStyle SequenceDelayFontName ActivityBorderColor
ClassStereotypeFontColor FolderStereotypeFontStyle NoteShadowing
SequenceDelayFontSize ActivityBorderThickness ClassStereotypeFontName
FooterFontColor NoteTextAlignment SequenceDelayFontStyle
ActivityDiamondFontColor ClassStereotypeFontSize FooterFontName
ObjectAttributeFontColor SequenceDividerBorderThickness
ActivityDiamondFontName ClassStereotypeFontStyle FooterFontSize
ObjectAttributeFontName SequenceDividerFontColor
ActivityDiamondFontSize CloudFontColor FooterFontStyle
ObjectAttributeFontSize SequenceDividerFontName
ActivityDiamondFontStyle CloudFontName FrameFontColor
ObjectAttributeFontStyle SequenceDividerFontSize ActivityFontColor
CloudFontSize FrameFontName ObjectBorderThickness
SequenceDividerFontStyle ActivityFontName CloudFontStyle FrameFontSize
ObjectFontColor SequenceGroupBodyBackgroundColor ActivityFontSize
CloudStereotypeFontColor FrameFontStyle ObjectFontName
SequenceGroupBorderThickness ActivityFontStyle CloudStereotypeFontName
FrameStereotypeFontColor ObjectFontSize SequenceGroupFontColor
ActorBackgroundColor CloudStereotypeFontSize FrameStereotypeFontName
ObjectFontStyle SequenceGroupFontName ActorBorderColor
CloudStereotypeFontStyle FrameStereotypeFontSize
ObjectStereotypeFontColor SequenceGroupFontSize ActorFontColor
ColorArrowSeparationSpace FrameStereotypeFontStyle
ObjectStereotypeFontName SequenceGroupFontStyle ActorFontName
ComponentBorderThickness GenericDisplay ObjectStereotypeFontSize
SequenceGroupHeaderFontColor ActorFontSize ComponentFontColor
Guillemet ObjectStereotypeFontStyle SequenceGroupHeaderFontName
ActorFontStyle ComponentFontName Handwritten PackageBorderThickness
SequenceGroupHeaderFontSize ActorStereotypeFontColor ComponentFontSize
HeaderFontColor PackageFontColor SequenceGroupHeaderFontStyle
ActorStereotypeFontName ComponentFontStyle HeaderFontName
PackageFontName SequenceLifeLineBorderColor ActorStereotypeFontSize
ComponentStereotypeFontColor HeaderFontSize PackageFontSize
SequenceLifeLineBorderThickness ActorStereotypeFontStyle
ComponentStereotypeFontName HeaderFontStyle PackageFontStyle
SequenceMessageAlignment AgentBorderThickness
ComponentStereotypeFontSize HexagonBorderThickness
PackageStereotypeFontColor SequenceMessageTextAlignment AgentFontColor
ComponentStereotypeFontStyle HexagonFontColor
PackageStereotypeFontName SequenceNewpageSeparatorColor AgentFontName
ComponentStyle HexagonFontName PackageStereotypeFontSize
SequenceParticipant AgentFontSize ConditionEndStyle HexagonFontSize
PackageStereotypeFontStyle SequenceParticipantBorderThickness
AgentFontStyle ConditionStyle HexagonFontStyle PackageStyle
SequenceReferenceAlignment AgentStereotypeFontColor ControlFontColor
HexagonStereotypeFontColor PackageTitleAlignment
SequenceReferenceBackgroundColor AgentStereotypeFontName
ControlFontName HexagonStereotypeFontName Padding
SequenceReferenceBorderThickness AgentStereotypeFontSize
ControlFontSize HexagonStereotypeFontSize PageBorderColor
SequenceReferenceFontColor AgentStereotypeFontStyle ControlFontStyle
HexagonStereotypeFontStyle PageExternalColor SequenceReferenceFontName
ArchimateBorderThickness ControlStereotypeFontColor HyperlinkColor
PageMargin SequenceReferenceFontSize ArchimateFontColor
ControlStereotypeFontName HyperlinkUnderline ParticipantFontColor
SequenceReferenceFontStyle ArchimateFontName ControlStereotypeFontSize
IconIEMandatoryColor ParticipantFontName
SequenceReferenceHeaderBackgroundColor ArchimateFontSize
ControlStereotypeFontStyle IconPackageBackgroundColor
ParticipantFontSize SequenceStereotypeFontColor ArchimateFontStyle
DatabaseFontColor IconPackageColor ParticipantFontStyle
SequenceStereotypeFontName ArchimateStereotypeFontColor
DatabaseFontName IconPrivateBackgroundColor ParticipantPadding
SequenceStereotypeFontSize ArchimateStereotypeFontName
DatabaseFontSize IconPrivateColor ParticipantStereotypeFontColor
SequenceStereotypeFontStyle ArchimateStereotypeFontSize
DatabaseFontStyle IconProtectedBackgroundColor
ParticipantStereotypeFontName Shadowing ArchimateStereotypeFontStyle
DatabaseStereotypeFontColor IconProtectedColor
ParticipantStereotypeFontSize StackFontColor ArrowFontColor
DatabaseStereotypeFontName IconPublicBackgroundColor
ParticipantStereotypeFontStyle StackFontName ArrowFontName
DatabaseStereotypeFontSize IconPublicColor PartitionBorderThickness
StackFontSize ArrowFontSize DatabaseStereotypeFontStyle
InterfaceFontColor PartitionFontColor StackFontStyle ArrowFontStyle
DefaultFontColor InterfaceFontName PartitionFontName
StackStereotypeFontColor ArrowHeadColor DefaultFontName
InterfaceFontSize PartitionFontSize StackStereotypeFontName
ArrowLollipopColor DefaultFontSize InterfaceFontStyle
PartitionFontStyle StackStereotypeFontSize ArrowMessageAlignment
DefaultFontStyle InterfaceStereotypeFontColor PathHoverColor
StackStereotypeFontStyle ArrowThickness DefaultMonospacedFontName
InterfaceStereotypeFontName PersonBorderThickness
StateAttributeFontColor ArtifactFontColor DefaultTextAlignment
InterfaceStereotypeFontSize PersonFontColor StateAttributeFontName
ArtifactFontName DesignedBackgroundColor InterfaceStereotypeFontStyle
PersonFontName StateAttributeFontSize ArtifactFontSize
DesignedBorderColor LabelFontColor PersonFontSize
StateAttributeFontStyle ArtifactFontStyle
DesignedDomainBorderThickness LabelFontName PersonFontStyle
StateBorderColor ArtifactStereotypeFontColor DesignedDomainFontColor
LabelFontSize PersonStereotypeFontColor StateFontColor
ArtifactStereotypeFontName DesignedDomainFontName LabelFontStyle
PersonStereotypeFontName StateFontName ArtifactStereotypeFontSize
DesignedDomainFontSize LabelStereotypeFontColor
PersonStereotypeFontSize StateFontSize ArtifactStereotypeFontStyle
DesignedDomainFontStyle LabelStereotypeFontName
PersonStereotypeFontStyle StateFontStyle BackgroundColor
DesignedDomainStereotypeFontColor LabelStereotypeFontSize
QueueBorderThickness StateMessageAlignment BiddableBackgroundColor
DesignedDomainStereotypeFontName LabelStereotypeFontStyle
QueueFontColor StereotypePosition BiddableBorderColor
DesignedDomainStereotypeFontSize LegendBorderThickness QueueFontName
StorageFontColor BoundaryFontColor DesignedDomainStereotypeFontStyle
LegendFontColor QueueFontSize StorageFontName BoundaryFontName
DiagramBorderColor LegendFontName QueueFontStyle StorageFontSize
BoundaryFontSize DiagramBorderThickness LegendFontSize
QueueStereotypeFontColor StorageFontStyle BoundaryFontStyle
DomainBackgroundColor LegendFontStyle QueueStereotypeFontName
StorageStereotypeFontColor BoundaryStereotypeFontColor
DomainBorderColor LexicalBackgroundColor QueueStereotypeFontSize
StorageStereotypeFontName BoundaryStereotypeFontName
DomainBorderThickness LexicalBorderColor QueueStereotypeFontStyle
StorageStereotypeFontSize BoundaryStereotypeFontSize DomainFontColor
LifelineStrategy Ranksep StorageStereotypeFontStyle
BoundaryStereotypeFontStyle DomainFontName Linetype
RectangleBorderThickness Style BoxPadding DomainFontSize
MachineBackgroundColor RectangleFontColor SvglinkTarget
CaptionFontColor DomainFontStyle MachineBorderColor RectangleFontName
SwimlaneBorderThickness CaptionFontName DomainStereotypeFontColor
MachineBorderThickness RectangleFontSize SwimlaneTitleFontColor
CaptionFontSize DomainStereotypeFontName MachineFontColor
RectangleFontStyle SwimlaneTitleFontName CaptionFontStyle
DomainStereotypeFontSize MachineFontName RectangleStereotypeFontColor
SwimlaneTitleFontSize CardBorderThickness DomainStereotypeFontStyle
MachineFontSize RectangleStereotypeFontName SwimlaneTitleFontStyle
CardFontColor Dpi MachineFontStyle RectangleStereotypeFontSize
SwimlaneWidth CardFontName EntityFontColor MachineStereotypeFontColor
RectangleStereotypeFontStyle SwimlaneWrapTitleWidth CardFontSize
EntityFontName MachineStereotypeFontName RequirementBackgroundColor
TabSize CardFontStyle EntityFontSize MachineStereotypeFontSize
RequirementBorderColor TimingFontColor CardStereotypeFontColor
EntityFontStyle MachineStereotypeFontStyle RequirementBorderThickness
TimingFontName CardStereotypeFontName EntityStereotypeFontColor
MaxAsciiMessageLength RequirementFontColor TimingFontSize
CardStereotypeFontSize EntityStereotypeFontName MaxMessageSize
RequirementFontName TimingFontStyle CardStereotypeFontStyle
EntityStereotypeFontSize MinClassWidth RequirementFontSize
TitleBorderRoundCorner CircledCharacterFontColor
EntityStereotypeFontStyle Monochrome RequirementFontStyle
TitleBorderThickness CircledCharacterFontName FileFontColor
NodeFontColor RequirementStereotypeFontColor TitleFontColor
CircledCharacterFontSize FileFontName NodeFontName
RequirementStereotypeFontName TitleFontName CircledCharacterFontStyle
FileFontSize NodeFontSize RequirementStereotypeFontSize TitleFontSize
CircledCharacterRadius FileFontStyle NodeFontStyle
RequirementStereotypeFontStyle TitleFontStyle ClassAttributeFontColor
FileStereotypeFontColor NodeStereotypeFontColor
ResponseMessageBelowArrow UsecaseBorderThickness
ClassAttributeFontName FileStereotypeFontName NodeStereotypeFontName
RoundCorner UsecaseFontColor ClassAttributeFontSize
FileStereotypeFontSize NodeStereotypeFontSize SameClassWidth
UsecaseFontName ClassAttributeFontStyle FileStereotypeFontStyle
NodeStereotypeFontStyle SequenceActorBorderThickness UsecaseFontSize
ClassAttributeIconSize FixCircleLabelOverlapping Nodesep
SequenceArrowThickness UsecaseFontStyle ClassBackgroundColor
FolderFontColor NoteBackgroundColor SequenceBoxBorderColor
UsecaseStereotypeFontColor ClassBorderColor FolderFontName
NoteBorderColor SequenceBoxFontColor UsecaseStereotypeFontName
ClassBorderThickness FolderFontSize NoteBorderThickness
SequenceBoxFontName UsecaseStereotypeFontSize ClassFontColor
FolderFontStyle NoteFontColor SequenceBoxFontSize
UsecaseStereotypeFontStyle ClassFontName FolderStereotypeFontColor
NoteFontName SequenceBoxFontStyle WrapWidth ClassFontSize
FolderStereotypeFontName NoteFontSize SequenceDelayFontColor
